---
title: "Final"
author: "Shijie An"
date: '2022-11-02'
output: html_document
---

https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0269201
```{r setup}
library(ggplot2)
library(tidyverse)
library(ggpubr)
```

```{r}
dep = read.csv("pone.0269201.s002.csv")

prop.table(table(stat(dep$depression)))

## GPA is character, has value of "decline"
dep <- dep[-which(dep$GPA == "decline"), ]
dep$GPA <- as.numeric(dep$GPA)
dep %>% ggplot(aes(x = GPA, fill = depression)) +
  geom_density(alpha = 0.9) + 
  scale_color_manual(c("red", "green", "blue"))
```

```{r}
dep %>% ggplot(aes(x = GPA, fill = STEM.major.clean)) + 
  geom_density(alpha = 0.5) +
  scale_color_manual(c("red", "yellow"))
```
分类
```{r}
dep <- read.csv("pone.0269201.s002.csv")
dep$depression <- ifelse(dep$depression == "yes", "yes", "no")
dep <- dep %>% mutate(GPA = as.numeric(GPA)) ## 这里不知道为啥没用
```

```{r}
missingCol <- grep("idep|ddep", colnames(dep))
dep[, missingCol][is.na(dep[, missingCol])] <- -1
dep[, -missingCol][is.na(dep[, -missingCol])] <- "Unknown"
```

```{r eval = FALSE}
for(i in 34:41) {
  print(stat(table(dep[i])))
  print(prop.table(stat(table(dep[i]))))
}
```

```{r plots, warning = FALSE}
dep %>% 
  ggplot(aes(x = depression, y = as.numeric(GPA))) + 
  geom_boxplot()

var <- list("STEM.major.clean", "race2", "division", "gender2", 
            "gen.stat2", "lgbtq2", "financially.stable2")
for(i in var) {
  count <- ggplot(data.frame(dep[, i]), aes(x = dep[, i], fill = dep$depression)) + 
    geom_bar(alpha = 0.3) + xlab(i)
  perc <- ggplot(data.frame(dep[, i]), aes(x = dep[, i], fill = dep$depression)) + 
    geom_bar(alpha = 0.3, position = "fill") + xlab(i)
  print(ggarrange(count, perc, labels = c("count", "perc"), ncol = 1, nrow = 2))
}
```

挑了3个显著的，race, gender, lgbtq, 最后加上一个gpa的boxplot
```{r plots}
count_race <- dep %>% ggplot(aes(x = race2, fill = depression)) + 
  geom_bar(alpha = 0.3)
perc_race <- dep %>% ggplot(aes(x = race2, fill = depression)) + 
  geom_bar(alpha = 0.3, position = "fill")
count_gender <- dep %>% ggplot(aes(x = gender2, fill = depression)) + 
  geom_bar(alpha = 0.3)
perc_gender <- dep %>% ggplot(aes(x = gender2, fill = depression)) + 
  geom_bar(alpha = 0.3, position = "fill")
count_lgbtq <- dep %>% ggplot(aes(x = lgbtq2, fill = depression)) + 
  geom_bar(alpha = 0.3)
perc_lgbtq <- dep %>% ggplot(aes(x = lgbtq2, fill = depression)) + 
  geom_bar(alpha = 0.3, position = "fill")
gpa <- dep %>% 
  ggplot(aes(x = depression, y = as.numeric(GPA))) + 
  geom_boxplot()
ggarrange(count_race, perc_race, count_gender, perc_gender, count_lgbtq,
          perc_lgbtq, gpa, ncol = 2, nrow = 4)

```

logistic regression
```{r}
# set.seed(1234)
# regression <- dep %>% select(depression, race2, division, gender2, 
#                              gen.stat2, lgbtq2, financially.stable2)
# intrain <- createDataPartition(regression$depression, p = 0.8, list = FALSE)
# train1 <- regression[intrain, ]
# test1 <- regression[-intrain, ]
# 
# 
# logisModel <- train(depression ~ ., data = train1, method = "glm", 
#                   preProcess = c("scale", "center"), 
#                   family = binomial(link = "logit"))
# logic_pred <- predict(logisModel, newdata = test1)
# l_cm <- confusionMatrix(logic_pred, factor(test1$depression))
# l_cm$overall

```
naive bayes
```{r}
# nb_fit <- train(depression ~ ., data = train1, method = "nb", 
#                 preProcess = c("scale", "center"))
# nb_pred <- predict(nb_fit, newdata = test1)
# nb_cm <- confusionMatrix(nb_pred, factor(test1$depression))
# nb_cm$overall

```



3. 选depression2 no



4. 选depression2 yes
```{r}
dep_s <- dep %>% filter(depression2 == "yes") %>% select(4:33)

namelist <- colnames(dep_s)
for(i in namelist) {
  print(table(dep_s[i]))
  print(prop.table(table(dep_s[i])))
  print("-----------------------------------")
}






```